networks:
  cnr-network:
    external: true

services:
  mysql-infologic:
    image: mysql:8.0
    container_name: INFOLOGIC-MYSQL
    restart: always
    env_file:
      - .env
    environment:
      MYSQL_ROOT_PASSWORD: ${MYSQL_ROOT_PASSWORD}
      MYSQL_DATABASE: infologic
    ports:
      - "3308:3306"
    networks:
      - cnr-network
    volumes:
      - mysql_data:/var/lib/mysql
      - ./mysql-init:/docker-entrypoint-initdb.d

  backend-infologic:
    build:
      context: ./infologic-backend
    container_name: INFOLOGIC-BACKEND
    depends_on:
      - mysql-infologic
      - transmisor-infologic
    env_file:
      - .env
    environment:
      MASTER_DB_URL: ${MASTER_DB_URL}
      MASTER_DB_USERNAME: ${MASTER_DB_USERNAME}
      MASTER_DB_PASSWORD: ${MASTER_DB_PASSWORD}
      SERVER_PORT: ${BACKEND_PORT}
    ports:
      - "${BACKEND_PORT}:${BACKEND_PORT}"
    networks:
      - cnr-network

  transmisor-infologic:
    build:
      context: ./infologic-transmisor
    container_name: INFOLOGIC-TRANSMISOR
    depends_on:
      - mysql-infologic
    env_file:
      - .env
    environment:
      MASTER_DB_URL: ${MASTER_DB_URL}
      MASTER_DB_USERNAME: ${MASTER_DB_USERNAME}
      MASTER_DB_PASSWORD: ${MASTER_DB_PASSWORD}
      TRANSMISOR_PORT: ${TRANSMISOR_PORT}
      ENDPOINT-FIRMAR: ${ENDPOINT_FIRMAR}
      CLIENTE_GOOGLE: ${CLIENTE_GOOGLE}
      CLIENTE_SECRET: ${CLIENTE_SECRET}
      REFRESH_TOKEN: ${REFRESH_TOKEN}
    ports:
      - "${TRANSMISOR_PORT}:${TRANSMISOR_PORT}"
    networks:
      - cnr-network
    volumes:
      - ./uploads:/app/uploads  # Montado para transmisor (si aplica)

  frontend-infologic:
    build:
      context: ./infologic-frontend
    container_name: INFOLOGIC-FRONTEND
    depends_on:
      - backend-infologic
    ports:
      - "80:80"
    networks:
      - cnr-network

  firmador-infologic:
    build:
      context: ./infologic-firmador
    container_name: INFOLOGIC-FIRMADOR
    depends_on:
      - transmisor-infologic
    ports:
      - "8113:8113"
    networks:
      - cnr-network
    volumes:
      - ./infologic-firmador/uploads:/app/uploads 

volumes:
  mysql_data:
